import 'emoji.dart';

//   - Private Use Area: U+E000–U+F8FF (6,400 characters),
final emojis = <Emoji>{
  Emoji('\u{e000}', '微笑', 'hehe.png'),
  Emoji('\u{e001}', '撇嘴', 'piezui.png'),
  Emoji('\u{e002}', '色', 'se.png'),
  Emoji('\u{e003}', '发呆', 'fadai.png'),
  Emoji('\u{e004}', '得意', 'deyi.png'),
  Emoji('\u{e005}', '流泪', 'liulei.png'),
  Emoji('\u{e006}', '害羞', 'haixiu.png'),
  Emoji('\u{e007}', '闭嘴', 'bizui.png'),
  Emoji('\u{e008}', '睡', 'shui.png'),
  Emoji('\u{e009}', '大哭', 'daku.png'),
  Emoji('\u{e00a}', '尴尬', 'ganga.png'),
  Emoji('\u{e00b}', '发怒', 'fanu.png'),
  Emoji('\u{e00c}', '调皮', 'tiaopi.png'),
  Emoji('\u{e00d}', '呲牙', 'ciya.png'),
  Emoji('\u{e00e}', '惊讶', 'jingya.png'),
  Emoji('\u{e00f}', '难过', 'nanguo.png'),
  Emoji('\u{e010}', '囧', 'jiong.png'),
  Emoji('\u{e011}', '抓狂', 'zhuakuang.png'),
  Emoji('\u{e012}', '吐', 'tu.png'),
  Emoji('\u{e013}', '偷笑', 'touxiao.png'),
  Emoji('\u{e014}', '愉快', 'yukuai.png'),
  Emoji('\u{e015}', '白眼', 'baiyan.png'),
  Emoji('\u{e016}', '傲慢', 'aoman.png'),
  Emoji('\u{e017}', '困', 'kun.png'),
  Emoji('\u{e018}', '惊恐', 'jingkong.png'),
  Emoji('\u{e019}', '流汗', 'liuhan.png'),
  Emoji('\u{e01a}', '憨笑', 'hanxiao.png'),
  Emoji('\u{e01b}', '悠闲', 'youxian.png'),
  Emoji('\u{e01c}', '奋斗', 'fendou.png'),
  Emoji('\u{e01d}', '咒骂', 'zhouma.png'),
  Emoji('\u{e01e}', '疑问', 'yiwen.png'),
  Emoji('\u{e01f}', '嘘', 'xu.png'),
  Emoji('\u{e020}', '晕', 'yun.png'),
  Emoji('\u{e021}', '衰', 'sui.png'),
  Emoji('\u{e022}', '骷髅', 'kulou.png'),
  Emoji('\u{e023}', '敲打', 'qiaoda.png'),
  Emoji('\u{e024}', '再见', 'zaininmadejian.png'),
  Emoji('\u{e025}', '擦汗', 'cahan.png'),
  Emoji('\u{e026}', '抠鼻', 'koubi.png'),
  Emoji('\u{e027}', '鼓掌', 'guzhang.png'),
  Emoji('\u{e028}', '坏笑', 'huaixiao.png'),
  Emoji('\u{e029}', '左哼哼', 'zuohengheng.png'),
  Emoji('\u{e02a}', '右哼哼', 'youhengheng.png'),
  Emoji('\u{e02b}', '哈欠', 'haqian.png'),
  Emoji('\u{e02c}', '鄙视', 'bishi.png'),
  Emoji('\u{e02d}', '委屈', 'weiqu.png'),
  Emoji('\u{e02e}', '快哭了', 'kuaikule.png'),
  Emoji('\u{e02f}', '阴险', 'yinxian.png'),
  Emoji('\u{e030}', '亲亲', 'qinqin.png'),
  Emoji('\u{e031}', '可怜', 'kelian.png'),
  Emoji('\u{e032}', '菜刀', 'caidao.png'),
  Emoji('\u{e033}', '西瓜', 'xigua.png'),
  Emoji('\u{e034}', '啤酒', 'pijiu.png'),
  Emoji('\u{e035}', '咖啡', 'kafei.png'),
  Emoji('\u{e036}', '猪头', 'zhutou.png'),
  Emoji('\u{e037}', '玫瑰', 'meigui.png'),
  Emoji('\u{e038}', '凋谢', 'diaoxie.png'),
  Emoji('\u{e039}', '嘴唇', 'zuichun.png'),
  Emoji('\u{e03a}', '爱心', 'aixin.png'),
  Emoji('\u{e03b}', '心碎', 'xinsui.png'),
  Emoji('\u{e03c}', '蛋糕', 'dangao.png'),
  Emoji('\u{e03d}', '炸弹', 'zhadan.png'),
  Emoji('\u{e03e}', '便便', 'bianbian.png'),
  Emoji('\u{e03f}', '月亮', 'yueliang.png'),
  Emoji('\u{e040}', '太阳', 'taiyang.png'),
  Emoji('\u{e041}', '拥抱', 'yongbao.png'),
  Emoji('\u{e042}', '强', 'qiang.png'),
  Emoji('\u{e043}', '弱', 'ruo.png'),
  Emoji('\u{e044}', '握手', 'woshou.png'),
  Emoji('\u{e045}', '胜利', 'shengli.png'),
  Emoji('\u{e046}', '抱拳', 'baoquan.png'),
  Emoji('\u{e047}', '勾引', 'gouyin.png'),
  Emoji('\u{e048}', '拳头', 'quantou.png'),
  Emoji('\u{e049}', 'OK', 'ok.png'),
  Emoji('\u{e04a}', '跳跳', 'tiaotiao.png'),
  Emoji('\u{e04b}', '发抖', 'fadou.png'),
  Emoji('\u{e04c}', '怄火', 'ohuo.png'),
  Emoji('\u{e04d}', '转圈', 'zhuanquan.png'),
  Emoji('\u{e04e}', '嘿哈', 'heiha.png'),
  Emoji('\u{e04f}', '捂脸', 'wulian.png'),
  Emoji('\u{e050}', '奸笑', 'jianxiao.png'),
  Emoji('\u{e051}', '机智', 'jizhi.png'),
  Emoji('\u{e052}', '皱眉', 'zhoumei.png'),
  Emoji('\u{e053}', '耶', 'ye.png'),
  Emoji('\u{e054}', '蜡烛', 'lazhu.png'),
  Emoji('\u{e055}', '红包', 'hongbao.png'),
  Emoji('\u{e056}', '吃瓜', 'chigua.png'),
  Emoji('\u{e057}', '加油', 'jiayou.png'),
  Emoji('\u{e058}', '汗', 'han.png'),
  Emoji('\u{e059}', '天啊', 'tiana.png'),
  Emoji('\u{e05a}', 'Emm', 'emm.png'),
  Emoji('\u{e05b}', '社会社会', 'shehuishehui.png'),
  Emoji('\u{e05c}', '旺柴', 'wangchai.png'),
  Emoji('\u{e05d}', '好的', 'haode.png'),
  Emoji('\u{e05e}', '打脸', 'dalian.png'),
  Emoji('\u{e05f}', '加油加油', 'jiayoujiayou.png'),
  Emoji('\u{e060}', '哇', 'wa.png'),
  Emoji('\u{e061}', '發', 'fa.png'),
  Emoji('\u{e062}', '福', 'fu.png'),
  Emoji('\u{e063}', '鸡', 'ji.png'),
};

Emoji? lookupByCode(int code) {
  try {
    return emojis.firstWhere((element) {
      return element.code.codeUnitAt(0) == code;
    });
  } catch (_) {
    return null;
  }
}
