services:
  apn-server:
    image: cylonix/tailchat-pnserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APN_AUTH_TYPE=${APN_AUTH_TYPE:-token}  # 'certificate' or 'token'
      - APN_KEY_PATH=/etc/apn/aps.p8
      - APN_KEY_ID=${APN_KEY_ID:-}
      - APN_TEAM_ID=${APN_TEAM_ID:-}
      - APN_BUNDLE_ID=${APN_BUNDLE_ID:-io.cylonix.tailchat}
      - APN_DEVELOPMENT=${APN_DEVELOPMENT:-true}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - ${APN_KEY_FILE:-./aps.p8}:/etc/apn/aps.p8:ro
    ports:
      - "${PORT:-9000}:9000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

volumes:
  redis_data: